[package]
name = "sawtooth-devmode-rust"
version = "0.1.0"
authors = ["Intel Corporation"]

[[bin]]
name = "devmode-rust"
path = "src/main.rs"

[dependencies]
clap = "2"
log = "0.3.0"
log4rs = "0.7.0"
rand = "0.4.2"
sawtooth_sdk = { path = "../../rust" }
